### ISSUE TITLE
SPS parse failure

### ISSUE THREAD

**Issue by koush** [angrycoding/sps-parser#1]
Here's the sprop-parameter-sets:

```
a=fmtp:96 packetization-mode=1;profile-level-id=4D0029;sprop-parameter-sets=J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA,KO48gA==
```

```
const sps = Buffer.from('J00AKedAPAET8s1AQEB8AAADAAQAAAMAoNGADqYAFfl//wKA', 'base64');
const pps = Buffer.from('KO48gA==', 'base64');
```

This may be invalid data? But it is what Wyze cameras are returning in their SDP (and throwing during parse).

**Comment by koush** [comment]
```
/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/bitstream.js:17
            byt = view.getUint8(byteoffset);
                       ^

Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at ExpGolomInit (/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/bitstream.js:17:24)
    at Bitstream.ExpGolomb (/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/bitstream.js:30:49)
    at hrd_parameters (/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/vui.js:9:40)
    at Object.getVUIParams (/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/vui.js:105:9)
    at Object.parse (/Volumes/Dev/scrypted/plugins/prebuffer-mixin/node_modules/h264-sps-parser/dist/index.js:111:34)
    at /Volumes/Dev/scrypted/plugins/prebuffer-mixin/<repl>.ts:1:4
    at Script.runInThisContext (node:vm:129:12)
    at runInContext (/Users/koush/.nvm/versions/node/v18.14.2/lib/node_modules/ts-node/src/repl.ts:673:19)
    at Object.execCommand (/Users/koush/.nvm/versions/node/v18.14.2/lib/node_modules/ts-node/src/repl.ts:639:28)
```

**Comment by angrycoding** [comment]
![image](https://user-images.githubusercontent.com/895042/232401611-7525ac7d-9e9e-4790-ba90-082b377b8906.png)
![image](https://user-images.githubusercontent.com/895042/232401652-fb783e0e-e9c5-4bf1-ab5d-71d5655dd4e6.png)

Hi! I don't know what you do, but given the fragment you've provided, it works for me perfectly

**Comment by koush** [comment]
I just realized this was the wrong repo! https://www.npmjs.com/package/h264-sps-parser
Sorry about that.

**Comment by angrycoding** [comment]
No problem
